### ISSUE TITLE
Make `Data Type` notebook

### ISSUE THREAD

**Issue by OmegaLambda1998** [panoptes/panoptes-tutorials#17]
> > @wtgee
> > So I was thinking of two options for this.
> > Either have all the basics (variable, lists, functions, types, etc...) in one mega notebook
> > Or split them up into different notebooks (variable.ipynb, lists.ipynb, functions.ipynb, etc...)
> 
> I think that a single notebook is okay for now and we will just evaluate that as it grows bigger.

Just paraphrasing what was discussed in the hack week:
We've decided to split it into a number of different notebooks.
These will include basic python ala Carpentries, as well as more specific packages like numpy, matplotlib, pandas, and astropy.

I'll make issues for each of these

_Originally posted by @MrPop2213 in https://github.com/panoptes/panoptes-tutorials/issues/11#issuecomment-585574620_

**Comment by geotaylo** [comment]
On it!
