### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by OmegaLambda1998** [panoptes/panoptes-tutorials#3]
Need to figure out what directory structure we should use.

**Comment by wtgee** [comment]
Let's move all the POCS specific notebooks to a `POCS` subfolder. This would be the POCS operation, the Scheduler, and the Horizon limits.

**Comment by OmegaLambda1998** [comment]
I can update that

**Comment by wtgee** [comment]
We might need to expand as we go but looks good for now.
