### ISSUE TITLE
Order of basic python notebooks

### ISSUE THREAD

**Issue by flamingotoelena** [panoptes/panoptes-tutorials#36]
We should stack the python notebooks in a particular order so that people using them (esp. beginners) can start sequentially from the very basics to something more complicated. So the notebook on matplotlib would require people to know about array manipulation, data types, etc so that notebook should come after those notebooks.
This could be easily done by numbering the notebooks so that people know what to start with, or what to jump to if they already have some basic knowledge.

**Comment by OmegaLambda1998** [comment]
I've done this, the order can probably be mixed around but it should be good for now!
